//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("canevasModel", "cellule_ibfk_1", "ligne", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(canevasModel.ligne), "cellule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.cellule), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "cellule_ibfk_2", "colonne", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(canevasModel.colonne), "cellule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.cellule), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "cellule_ibfk_3", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(canevasModel.user), "cellule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.cellule), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "colonne_ibfk_1", "tableau", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(canevasModel.tableau), "colonne", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.colonne), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "ligne_ibfk_1", "tableau", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(canevasModel.tableau), "ligne", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.ligne), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "unit_struct_ibfk_1", "unit_struct", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(canevasModel.unit_struct), "unit_struct1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.unit_struct), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "user_ibfk_1", "unit_struct", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(canevasModel.unit_struct), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.user), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "droit_remplissage_ibfk_1", "tableau", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(canevasModel.tableau), "droit_remplissage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.droit_remplissage), true)]
[assembly: EdmRelationshipAttribute("canevasModel", "droit_remplissage_ibfk_2", "unit_struct", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(canevasModel.unit_struct), "droit_remplissage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(canevasModel.droit_remplissage), true)]

#endregion

namespace canevasModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class canevasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new canevasEntities object using the connection string found in the 'canevasEntities' section of the application configuration file.
        /// </summary>
        public canevasEntities() : base("name=canevasEntities", "canevasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new canevasEntities object.
        /// </summary>
        public canevasEntities(string connectionString) : base(connectionString, "canevasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new canevasEntities object.
        /// </summary>
        public canevasEntities(EntityConnection connection) : base(connection, "canevasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cellule> cellules
        {
            get
            {
                if ((_cellules == null))
                {
                    _cellules = base.CreateObjectSet<cellule>("cellules");
                }
                return _cellules;
            }
        }
        private ObjectSet<cellule> _cellules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<colonne> colonnes
        {
            get
            {
                if ((_colonnes == null))
                {
                    _colonnes = base.CreateObjectSet<colonne>("colonnes");
                }
                return _colonnes;
            }
        }
        private ObjectSet<colonne> _colonnes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ligne> lignes
        {
            get
            {
                if ((_lignes == null))
                {
                    _lignes = base.CreateObjectSet<ligne>("lignes");
                }
                return _lignes;
            }
        }
        private ObjectSet<ligne> _lignes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tableau> tableaux
        {
            get
            {
                if ((_tableaux == null))
                {
                    _tableaux = base.CreateObjectSet<tableau>("tableaux");
                }
                return _tableaux;
            }
        }
        private ObjectSet<tableau> _tableaux;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<unit_struct> unit_struct
        {
            get
            {
                if ((_unit_struct == null))
                {
                    _unit_struct = base.CreateObjectSet<unit_struct>("unit_struct");
                }
                return _unit_struct;
            }
        }
        private ObjectSet<unit_struct> _unit_struct;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<droit_remplissage> droit_remplissage
        {
            get
            {
                if ((_droit_remplissage == null))
                {
                    _droit_remplissage = base.CreateObjectSet<droit_remplissage>("droit_remplissage");
                }
                return _droit_remplissage;
            }
        }
        private ObjectSet<droit_remplissage> _droit_remplissage;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cellules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocellules(cellule cellule)
        {
            base.AddObject("cellules", cellule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the colonnes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocolonnes(colonne colonne)
        {
            base.AddObject("colonnes", colonne);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lignes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolignes(ligne ligne)
        {
            base.AddObject("lignes", ligne);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tableaux EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotableaux(tableau tableau)
        {
            base.AddObject("tableaux", tableau);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the unit_struct EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTounit_struct(unit_struct unit_struct)
        {
            base.AddObject("unit_struct", unit_struct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the droit_remplissage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodroit_remplissage(droit_remplissage droit_remplissage)
        {
            base.AddObject("droit_remplissage", droit_remplissage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="cellule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cellule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cellule object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="valeur">Initial value of the valeur property.</param>
        public static cellule Createcellule(global::System.Int32 id, global::System.String valeur)
        {
            cellule cellule = new cellule();
            cellule.Id = id;
            cellule.valeur = valeur;
            return cellule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom_cellule
        {
            get
            {
                return _nom_cellule;
            }
            set
            {
                Onnom_celluleChanging(value);
                ReportPropertyChanging("nom_cellule");
                _nom_cellule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom_cellule");
                Onnom_celluleChanged();
            }
        }
        private global::System.String _nom_cellule;
        partial void Onnom_celluleChanging(global::System.String value);
        partial void Onnom_celluleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valeur
        {
            get
            {
                return _valeur;
            }
            set
            {
                OnvaleurChanging(value);
                ReportPropertyChanging("valeur");
                _valeur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valeur");
                OnvaleurChanged();
            }
        }
        private global::System.String _valeur;
        partial void OnvaleurChanging(global::System.String value);
        partial void OnvaleurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_ligne
        {
            get
            {
                return _id_ligne;
            }
            set
            {
                Onid_ligneChanging(value);
                ReportPropertyChanging("id_ligne");
                _id_ligne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_ligne");
                Onid_ligneChanged();
            }
        }
        private Nullable<global::System.Int32> _id_ligne;
        partial void Onid_ligneChanging(Nullable<global::System.Int32> value);
        partial void Onid_ligneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_colonne
        {
            get
            {
                return _id_colonne;
            }
            set
            {
                Onid_colonneChanging(value);
                ReportPropertyChanging("id_colonne");
                _id_colonne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_colonne");
                Onid_colonneChanged();
            }
        }
        private Nullable<global::System.Int32> _id_colonne;
        partial void Onid_colonneChanging(Nullable<global::System.Int32> value);
        partial void Onid_colonneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private Nullable<global::System.Int32> _id_user;
        partial void Onid_userChanging(Nullable<global::System.Int32> value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_1", "ligne")]
        public ligne ligne
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ligne>("canevasModel.cellule_ibfk_1", "ligne").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ligne>("canevasModel.cellule_ibfk_1", "ligne").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ligne> ligneReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ligne>("canevasModel.cellule_ibfk_1", "ligne");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ligne>("canevasModel.cellule_ibfk_1", "ligne", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_2", "colonne")]
        public colonne colonne
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<colonne>("canevasModel.cellule_ibfk_2", "colonne").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<colonne>("canevasModel.cellule_ibfk_2", "colonne").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<colonne> colonneReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<colonne>("canevasModel.cellule_ibfk_2", "colonne");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<colonne>("canevasModel.cellule_ibfk_2", "colonne", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_3", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("canevasModel.cellule_ibfk_3", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("canevasModel.cellule_ibfk_3", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("canevasModel.cellule_ibfk_3", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("canevasModel.cellule_ibfk_3", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="colonne")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class colonne : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new colonne object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="intitule">Initial value of the intitule property.</param>
        /// <param name="type_colonne">Initial value of the type_colonne property.</param>
        /// <param name="id_tab">Initial value of the id_tab property.</param>
        public static colonne Createcolonne(global::System.Int32 id, global::System.String intitule, global::System.String type_colonne, global::System.Int32 id_tab)
        {
            colonne colonne = new colonne();
            colonne.Id = id;
            colonne.intitule = intitule;
            colonne.type_colonne = type_colonne;
            colonne.id_tab = id_tab;
            return colonne;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String intitule
        {
            get
            {
                return _intitule;
            }
            set
            {
                OnintituleChanging(value);
                ReportPropertyChanging("intitule");
                _intitule = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("intitule");
                OnintituleChanged();
            }
        }
        private global::System.String _intitule;
        partial void OnintituleChanging(global::System.String value);
        partial void OnintituleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type_colonne
        {
            get
            {
                return _type_colonne;
            }
            set
            {
                Ontype_colonneChanging(value);
                ReportPropertyChanging("type_colonne");
                _type_colonne = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type_colonne");
                Ontype_colonneChanged();
            }
        }
        private global::System.String _type_colonne;
        partial void Ontype_colonneChanging(global::System.String value);
        partial void Ontype_colonneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tab
        {
            get
            {
                return _id_tab;
            }
            set
            {
                Onid_tabChanging(value);
                ReportPropertyChanging("id_tab");
                _id_tab = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_tab");
                Onid_tabChanged();
            }
        }
        private global::System.Int32 _id_tab;
        partial void Onid_tabChanging(global::System.Int32 value);
        partial void Onid_tabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_2", "cellule")]
        public EntityCollection<cellule> cellules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cellule>("canevasModel.cellule_ibfk_2", "cellule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cellule>("canevasModel.cellule_ibfk_2", "cellule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "colonne_ibfk_1", "tableau")]
        public tableau tableau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.colonne_ibfk_1", "tableau").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.colonne_ibfk_1", "tableau").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tableau> tableauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.colonne_ibfk_1", "tableau");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tableau>("canevasModel.colonne_ibfk_1", "tableau", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="droit_remplissage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class droit_remplissage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new droit_remplissage object.
        /// </summary>
        /// <param name="id_tab">Initial value of the Id_tab property.</param>
        /// <param name="id_unit">Initial value of the Id_unit property.</param>
        /// <param name="fermer">Initial value of the fermer property.</param>
        public static droit_remplissage Createdroit_remplissage(global::System.Int32 id_tab, global::System.Int32 id_unit, global::System.Int32 fermer)
        {
            droit_remplissage droit_remplissage = new droit_remplissage();
            droit_remplissage.Id_tab = id_tab;
            droit_remplissage.Id_unit = id_unit;
            droit_remplissage.fermer = fermer;
            return droit_remplissage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_tab
        {
            get
            {
                return _Id_tab;
            }
            set
            {
                if (_Id_tab != value)
                {
                    OnId_tabChanging(value);
                    ReportPropertyChanging("Id_tab");
                    _Id_tab = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_tab");
                    OnId_tabChanged();
                }
            }
        }
        private global::System.Int32 _Id_tab;
        partial void OnId_tabChanging(global::System.Int32 value);
        partial void OnId_tabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_unit
        {
            get
            {
                return _Id_unit;
            }
            set
            {
                if (_Id_unit != value)
                {
                    OnId_unitChanging(value);
                    ReportPropertyChanging("Id_unit");
                    _Id_unit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_unit");
                    OnId_unitChanged();
                }
            }
        }
        private global::System.Int32 _Id_unit;
        partial void OnId_unitChanging(global::System.Int32 value);
        partial void OnId_unitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fermer
        {
            get
            {
                return _fermer;
            }
            set
            {
                OnfermerChanging(value);
                ReportPropertyChanging("fermer");
                _fermer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fermer");
                OnfermerChanged();
            }
        }
        private global::System.Int32 _fermer;
        partial void OnfermerChanging(global::System.Int32 value);
        partial void OnfermerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "droit_remplissage_ibfk_1", "tableau")]
        public tableau tableau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.droit_remplissage_ibfk_1", "tableau").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.droit_remplissage_ibfk_1", "tableau").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tableau> tableauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.droit_remplissage_ibfk_1", "tableau");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tableau>("canevasModel.droit_remplissage_ibfk_1", "tableau", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "droit_remplissage_ibfk_2", "unit_struct")]
        public unit_struct unit_struct
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.droit_remplissage_ibfk_2", "unit_struct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.droit_remplissage_ibfk_2", "unit_struct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<unit_struct> unit_structReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.droit_remplissage_ibfk_2", "unit_struct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<unit_struct>("canevasModel.droit_remplissage_ibfk_2", "unit_struct", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="ligne")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ligne : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ligne object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="intitule">Initial value of the intitule property.</param>
        public static ligne Createligne(global::System.Int32 id, global::System.String intitule)
        {
            ligne ligne = new ligne();
            ligne.Id = id;
            ligne.intitule = intitule;
            return ligne;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String intitule
        {
            get
            {
                return _intitule;
            }
            set
            {
                OnintituleChanging(value);
                ReportPropertyChanging("intitule");
                _intitule = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("intitule");
                OnintituleChanged();
            }
        }
        private global::System.String _intitule;
        partial void OnintituleChanging(global::System.String value);
        partial void OnintituleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_tab
        {
            get
            {
                return _id_tab;
            }
            set
            {
                Onid_tabChanging(value);
                ReportPropertyChanging("id_tab");
                _id_tab = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_tab");
                Onid_tabChanged();
            }
        }
        private Nullable<global::System.Int32> _id_tab;
        partial void Onid_tabChanging(Nullable<global::System.Int32> value);
        partial void Onid_tabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_1", "cellule")]
        public EntityCollection<cellule> cellules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cellule>("canevasModel.cellule_ibfk_1", "cellule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cellule>("canevasModel.cellule_ibfk_1", "cellule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "ligne_ibfk_1", "tableau")]
        public tableau tableau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.ligne_ibfk_1", "tableau").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.ligne_ibfk_1", "tableau").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tableau> tableauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tableau>("canevasModel.ligne_ibfk_1", "tableau");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tableau>("canevasModel.ligne_ibfk_1", "tableau", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="tableau")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tableau : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tableau object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom_tab">Initial value of the nom_tab property.</param>
        public static tableau Createtableau(global::System.Int32 id, global::System.String nom_tab)
        {
            tableau tableau = new tableau();
            tableau.Id = id;
            tableau.nom_tab = nom_tab;
            return tableau;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_tab
        {
            get
            {
                return _nom_tab;
            }
            set
            {
                Onnom_tabChanging(value);
                ReportPropertyChanging("nom_tab");
                _nom_tab = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_tab");
                Onnom_tabChanged();
            }
        }
        private global::System.String _nom_tab;
        partial void Onnom_tabChanging(global::System.String value);
        partial void Onnom_tabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> etat
        {
            get
            {
                return _etat;
            }
            set
            {
                OnetatChanging(value);
                ReportPropertyChanging("etat");
                _etat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("etat");
                OnetatChanged();
            }
        }
        private Nullable<global::System.Int32> _etat;
        partial void OnetatChanging(Nullable<global::System.Int32> value);
        partial void OnetatChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "colonne_ibfk_1", "colonne")]
        public EntityCollection<colonne> colonnes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<colonne>("canevasModel.colonne_ibfk_1", "colonne");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<colonne>("canevasModel.colonne_ibfk_1", "colonne", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "ligne_ibfk_1", "ligne")]
        public EntityCollection<ligne> lignes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ligne>("canevasModel.ligne_ibfk_1", "ligne");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ligne>("canevasModel.ligne_ibfk_1", "ligne", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "droit_remplissage_ibfk_1", "droit_remplissage")]
        public EntityCollection<droit_remplissage> droit_remplissage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<droit_remplissage>("canevasModel.droit_remplissage_ibfk_1", "droit_remplissage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<droit_remplissage>("canevasModel.droit_remplissage_ibfk_1", "droit_remplissage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="unit_struct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class unit_struct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new unit_struct object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="intitule">Initial value of the intitule property.</param>
        public static unit_struct Createunit_struct(global::System.Int32 id, global::System.String intitule)
        {
            unit_struct unit_struct = new unit_struct();
            unit_struct.Id = id;
            unit_struct.intitule = intitule;
            return unit_struct;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String intitule
        {
            get
            {
                return _intitule;
            }
            set
            {
                OnintituleChanging(value);
                ReportPropertyChanging("intitule");
                _intitule = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("intitule");
                OnintituleChanged();
            }
        }
        private global::System.String _intitule;
        partial void OnintituleChanging(global::System.String value);
        partial void OnintituleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> unite_mere
        {
            get
            {
                return _unite_mere;
            }
            set
            {
                Onunite_mereChanging(value);
                ReportPropertyChanging("unite_mere");
                _unite_mere = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unite_mere");
                Onunite_mereChanged();
            }
        }
        private Nullable<global::System.Int32> _unite_mere;
        partial void Onunite_mereChanging(Nullable<global::System.Int32> value);
        partial void Onunite_mereChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "unit_struct_ibfk_1", "unit_struct1")]
        public EntityCollection<unit_struct> unit_struct1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "unit_struct_ibfk_1", "unit_struct")]
        public unit_struct unit_struct2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<unit_struct> unit_struct2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<unit_struct>("canevasModel.unit_struct_ibfk_1", "unit_struct", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "user_ibfk_1", "user")]
        public EntityCollection<user> users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user>("canevasModel.user_ibfk_1", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user>("canevasModel.user_ibfk_1", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "droit_remplissage_ibfk_2", "droit_remplissage")]
        public EntityCollection<droit_remplissage> droit_remplissage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<droit_remplissage>("canevasModel.droit_remplissage_ibfk_2", "droit_remplissage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<droit_remplissage>("canevasModel.droit_remplissage_ibfk_2", "droit_remplissage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="canevasModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        /// <param name="prenom">Initial value of the prenom property.</param>
        /// <param name="login">Initial value of the login property.</param>
        /// <param name="mdp">Initial value of the mdp property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="unit_struct">Initial value of the unit_struct property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String nom, global::System.String prenom, global::System.String login, global::System.String mdp, global::System.String type, global::System.Int32 unit_struct)
        {
            user user = new user();
            user.Id = id;
            user.nom = nom;
            user.prenom = prenom;
            user.login = login;
            user.mdp = mdp;
            user.type = type;
            user.unit_struct = unit_struct;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mdp
        {
            get
            {
                return _mdp;
            }
            set
            {
                OnmdpChanging(value);
                ReportPropertyChanging("mdp");
                _mdp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mdp");
                OnmdpChanged();
            }
        }
        private global::System.String _mdp;
        partial void OnmdpChanging(global::System.String value);
        partial void OnmdpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unit_struct
        {
            get
            {
                return _unit_struct;
            }
            set
            {
                Onunit_structChanging(value);
                ReportPropertyChanging("unit_struct");
                _unit_struct = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unit_struct");
                Onunit_structChanged();
            }
        }
        private global::System.Int32 _unit_struct;
        partial void Onunit_structChanging(global::System.Int32 value);
        partial void Onunit_structChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.String _created_at;
        partial void Oncreated_atChanging(global::System.String value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.String _updated_at;
        partial void Onupdated_atChanging(global::System.String value);
        partial void Onupdated_atChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "cellule_ibfk_3", "cellule")]
        public EntityCollection<cellule> cellules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cellule>("canevasModel.cellule_ibfk_3", "cellule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cellule>("canevasModel.cellule_ibfk_3", "cellule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("canevasModel", "user_ibfk_1", "unit_struct")]
        public unit_struct unit_struct1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.user_ibfk_1", "unit_struct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.user_ibfk_1", "unit_struct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<unit_struct> unit_struct1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<unit_struct>("canevasModel.user_ibfk_1", "unit_struct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<unit_struct>("canevasModel.user_ibfk_1", "unit_struct", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
